name: Issue Bot
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  issue_bot:
    name: Issue Bot
    if: ${{ !github.event.issue.pull_request }} && github.repository == 'raycast/extensions'
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Bot
        run: bun create github.com/raycast/github-action-bot
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}
      - name: Run bot
        run: |
          cd github-action-bot
          bun run index.ts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}
          SCRIPT: "scripts/bots/issue-bot.ts"

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Notify Failure to Slack
        if: failure()
        uses: raycast/github-actions/slack-send@master
        with:
          webhook: ${{ secrets.SLACK_RELEASE_CHANNEL_WEBHOOK_URL }}
          color: "danger"
          text: |
            :no_entry_sign: ${{ github.workflow }} has failed
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Action logs> | <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|Commit: ${{ env.SHORT_SHA }}>
