name: PR Bot
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "extensions/**"
      - "docs/**"
    branches: [main, master]

jobs:
  pr-bot:
    if: github.repository == 'raycast/extensions'
    name: "PR Bot"
    runs-on: ubuntu-latest
    steps:
      - name: Get changed extensions
        id: get_changed_extensions
        uses: raycast/github-actions/get-changed-extensions@v1.18.0
        with:
          github_event_name: ${{ github.event_name }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Bot
        run: bun create github.com/raycast/github-action-bot
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}
      - name: Run bot
        run: |
          cd github-action-bot
          bun run index.ts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}
          SCRIPT: "scripts/bots/pr-bot.ts"
          CHANGED_EXTENSIONS: ${{ steps.get_changed_extensions.outputs.paths }}

      - name: Notify Failure to Slack
        if: failure()
        uses: raycast/github-actions/slack-send@master
        with:
          webhook: ${{ secrets.SLACK_RELEASE_CHANNEL_WEBHOOK_URL }}
          color: "danger"
          text: |
            :no_entry_sign: ${{ github.workflow }} has failed
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Action logs> | <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|Commit: ${{ github.sha }}>
